//! Checkpoint probe: `cargo run --example probe -- <manifest> <ckpt> [task] [track] [index]`
//! Regenerates the pool deterministically, greedy-decodes one eval instance
//! with the checkpoint weights, and prints every non-teacher-guided step
//! (each step feeds the model's own previous output).

use burn::backend::{Autodiff, NdArray, ndarray::NdArrayDevice};
use burn::tensor::{Int, Tensor, TensorData};
use generalist::{
    harness::{RunConfig, generate},
    model::LoopedConfig,
    tasks::TaskRegistry,
    train::Trainer,
};

type B = Autodiff<NdArray>;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let manifest = args.get(1).map(|s| s.as_str()).unwrap_or("configs/scale-probe.json");
    let ckpt = args.get(2).map(|s| s.as_str()).unwrap_or("checkpoints-scale-probe/step000200.mpk");
    let task = args.get(3).map(|s| s.as_str()).unwrap_or("parity");
    let track = args.get(4).map(|s| s.as_str()).unwrap_or("B");
    let index: usize = args.get(5).and_then(|s| s.parse().ok()).unwrap_or(0);

    let device = NdArrayDevice::default();
    let run = RunConfig::load_json(std::path::Path::new(manifest)).expect("manifest");
    let registry = TaskRegistry::builtin();
    let pool = generate(&run.experiment, &registry);
    let cell: Vec<_> = pool
        .iter()
        .filter(|i| i.info.task == task && format!("{:?}", i.info.track) == track)
        .collect();
    let inst = cell[index % cell.len()];
    println!("task={} track={} k={} cell_size={}", task, track, inst.info.k, cell.len());
    println!("--- prompt ---");
    print!("{}", String::from_utf8_lossy(&inst.prompt));
    println!("--- expected target ---");
    println!("{}", String::from_utf8_lossy(&inst.target));

    let model = Trainer::<B>::load_checkpoint(
        &run.model,
        std::path::Path::new(ckpt),
        &device,
    );
    let cfg: LoopedConfig = run.model.clone();

    // Greedy free-running decode; every step below is non-teacher-guided.
    // Shifted inputs (training convention): feed [PAD] ++ generated bytes
    // and read the last position, which predicts the next byte.
    let mut ids: Vec<i64> = inst.prompt_ids();
    let mut out_bytes: Vec<u8> = vec![];
    let mut free_steps = 0usize;
    loop {
        let t = ids.len() + 1;
        if t >= cfg.max_seq_len {
            println!("(hit max_seq_len)");
            break;
        }
        let mut shifted = vec![0i64];
        shifted.extend_from_slice(&ids);
        let tokens =
            Tensor::<B, 2, Int>::from_data(TensorData::new(shifted, [1, t]), &device);
        let mode = if std::env::args().any(|a| a == "fixed") { generalist::model::StopMode::Fixed { loops: 8 } } else { generalist::model::StopMode::Act };
        let out = model.forward(tokens, &cfg, mode, &[t], None);
        let v = cfg.vocab_size;
        let logits = out.logits.slice([0..1, t - 1..t, 0..v]).reshape([v]);
        let data = logits.into_data();
        let row = data.as_slice::<f32>().unwrap();
        let mut top: Vec<(usize, f32)> = row.iter().copied().enumerate().collect();
        top.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        let next = top[0].0 as i64;
        free_steps += 1;
        let ch = next as u8 as char;
        println!(
            "decode step {free_steps}: emit {ch:?} (byte {next}) top3={:?} halt={:.2} loops={}",
            top.iter().take(3).map(|(i, p)| (*i, *p)).collect::<Vec<_>>(),
            out.mean_halt,
            out.steps_used,
        );
        if (next == generalist::harness::EOS as i64 && !out_bytes.is_empty())
            || out_bytes.len() >= 8
        {
            if next == generalist::harness::EOS as i64 {
                println!("(EOS stop)");
            }
            break;
        }
        ids.push(next);
        out_bytes.push(next as u8);
    }
    let text = String::from_utf8_lossy(&out_bytes);
    let expected = String::from_utf8_lossy(&inst.target);
    let stripped: String = text.trim_matches('\0').to_string();
    println!("free-running steps: {free_steps}");
    println!("generated: {text:?} expected: {expected:?}");
    println!(
        "verdict: {} (ignoring stray EOS: {})",
        if text == expected { "MATCH" } else { "MISMATCH" },
        if stripped == expected { "MATCH" } else { "MISMATCH" },
    );
}
